### PR TITLE
Add support for Swift 🍎

### PR DESCRIPTION
**Pull request by justinhhorner**
Adding basic Swift support to the randomness party 🎉

### CODE REVIEW

**Comment by whitep4nth3r** [comment]
This looks great! I'll be taking a proper look at merging on stream tomorrow :) Thank you!

**Comment by whitep4nth3r** [comment]
Hello! Please could you rebase with main and fix up some conflicts? I just merged in a PR that reorganised some of the constants and things, which has made contributing easier in the long run. Thanks for your PR!

**Comment by justinhhorner** [comment]
@whitep4nth3r Done! ✅

**Comment by whitep4nth3r** [comment]
@all-contributors please add @justinhhorner for code

**Pull request merged**
