### PR TITLE
Added VBA (showing my age :-( )

### PR DESCRIPTION
**Pull request by Mark-Phillipson**
Why can't I forget this language :-)

### CODE REVIEW

**Comment by whitep4nth3r** [comment]
Hey! Thank you for the PR! Did you branch off an updated main branch? Just wondering if you might be able to resolve the conflicts? Thanks!

**Comment by whitep4nth3r** [comment]
Make sure you add your GitHub username to the contributors file!

**Comment by Mark-Phillipson** [comment]
I have updated the contributors file. By the way on twitch I am,  MarcusVoiceProgrammer

**Comment by whitep4nth3r** [comment]
Hey! I'm starting work on turning this into a node module tomorrow, so if you'd like your code in the node module, please take a look at the addNewLine() helper and integrate this with the VBA case. Thanks!

**Comment by Mark-Phillipson** [comment]
Okay I'm now using the addNewLine() helper

**Comment by whitep4nth3r** [comment]
@all-contributors please add @Mark-Phillipson for code

**Pull request merged**
