### PR TITLE
added support for scala :)

### PR DESCRIPTION
**Pull request by firephil**
added support for scala :) it should be ok

### CODE REVIEW

**Comment by whitep4nth3r** [comment]
Thank you! Make sure to add yourself to the `Contributor` object in helpers.js!

**Comment by whitep4nth3r** [comment]
I will take a proper look at this and merge it on stream on Wednesday! 🔥

**Comment by firephil** [comment]
> I will take a proper look at this and merge it on stream on Wednesday! 🔥

thanks, keep up the good work :)

**Comment by whitep4nth3r** [comment]
Hello! Please could you rebase with main and fix up some conflicts? I just merged in a PR that reorganised some of the constants and things, which has made contributing easier in the long run. Thanks for your PR!

**Comment by whitep4nth3r** [comment]
Hey! I'm starting work on turning this into a node module tomorrow, so if you'd like your code in the node module, please take a look at the merge conflicts and rebase your branch with main. There's also a new helper - addNewLine() which I'd like to see in the switch case for scala. Thanks!

**Pull request closed without merging**
